//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgTagFanOut.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ImgTagFanOut.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        public static string ShowDone {
            get {
                return ResourceManager.GetString("ShowDone", resourceCulture);
            }
        }
        
        public static string ShowDoneOn {
            get {
                return ResourceManager.GetString("ShowDoneOn", resourceCulture);
            }
        }
        
        public static string ShowDoneOff {
            get {
                return ResourceManager.GetString("ShowDoneOff", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string Locate {
            get {
                return ResourceManager.GetString("Locate", resourceCulture);
            }
        }
        
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        public static string SelectExportFolder {
            get {
                return ResourceManager.GetString("SelectExportFolder", resourceCulture);
            }
        }
        
        public static string SelectWorkingFolder {
            get {
                return ResourceManager.GetString("SelectWorkingFolder", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string NotFoundSkipped {
            get {
                return ResourceManager.GetString("NotFoundSkipped", resourceCulture);
            }
        }
        
        public static string AlreadyAt {
            get {
                return ResourceManager.GetString("AlreadyAt", resourceCulture);
            }
        }
        
        public static string CopiedTo {
            get {
                return ResourceManager.GetString("CopiedTo", resourceCulture);
            }
        }
        
        public static string CollectExp {
            get {
                return ResourceManager.GetString("CollectExp", resourceCulture);
            }
        }
        
        public static string ConsentErrorTracking {
            get {
                return ResourceManager.GetString("ConsentErrorTracking", resourceCulture);
            }
        }
        
        public static string ConsentAccept {
            get {
                return ResourceManager.GetString("ConsentAccept", resourceCulture);
            }
        }
        
        public static string ConsentDecline {
            get {
                return ResourceManager.GetString("ConsentDecline", resourceCulture);
            }
        }
    }
}
